eva.mongo.uri=mongodb://|eva.mongo.user|:|eva.mongo.passwd.url-encoded|@|eva.mongo.host|/admin
eva.mongo.accessioning-database=eva_accession_sharded

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://|eva.evapro.jdbc.url|:|eva.evapro.jdbc.port|/|eva.evapro.jdbc.db|
spring.datasource.username=|eva.evapro.jdbc.user|
spring.datasource.password=|eva.evapro.jdbc.password|
